name: Clean Workflow Logs

on:
  schedule:
    - cron: "0 0 * * 6"  # Runs "At 00:00 on Monday." (see https://crontab.guru)

jobs:
  clean-logs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: igorjs/gh-actions-clean-workflow@v4
        with:
          days_old: "7" # optional, default value: "7"
          runs_to_keep: "20" # optional, default value: "0"
