name: DemoQA Selenium ubuntu-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '0 6,8,10,12,14,16,18,20,22 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1
        # Run Docker Compose Action
      - uses: adambirds/docker-compose-action@v1.5.0
        with:
                  compose-file: "./docker/docker-compose.yml"
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 21
      - name:  Install Google Chrome # Using shell script to install Google Chrome
        run:   |
                chmod +x ./scripts/InstallChrome.sh
                            ./scripts/InstallChrome.sh 
  
      - name: Maven Verify
        run: mvn -B clean test

      - name: Deploy
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./ExtentReports
