name: Feature Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '0 1,2,3,5,6,7,9,10,11 * * *'

jobs:

  test:
      
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20
          cache: maven

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version
      - name: Maven Package
        run: mvn -B clean package -DskipTests
          
      - name: Maven Verify
        run: mvn -B clean verify
