name: DemoQA Selenium Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '0 12,13,14,15,16,17,18,19,20 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up JDK 20
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: 20
          cache: maven
          
      - name: Maven Verify
        run: mvn -B clean test

      - name: Deploy
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./ExtentReports
