name: DemoQA Selenium Windows-latest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
     - cron: '0 6,8,10,12,14,16,18,20,22 * * *'

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 20
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: 20
          
      - name: Maven Verify
        run: mvn -B clean test

      - name: Deploy
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./ExtentReports
